title: NeuroTraxx
tagline: "Precision neuroscience. Advancing exploration and navigation."
description: "Discover NeuroTraxx — the next-generation platform delivering powerful, intuitive tools for subcortical navigation and mapping. Precision neuroscience at your fingertips."
url: "https://neurotraxx.com"
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
